version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Changing to logic-legends-app directory..."
      - |
        cd logic-legends-app || { echo "Error: logic-legends-app directory not found!"; exit 1; }
        echo "Installing dependencies..."
        if [ -f package-lock.json ]; then 
          echo "Using npm ci"
          npm ci
        else 
          echo "Lockfile not found, using npm install"
          npm install
        fi
        echo "Dependencies installed successfully"
      
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building TypeScript application..."
      - |
        cd logic-legends-app
        npm run build
        echo "Build completed on `date`"
      
  post_build:
    commands:
      - echo "Post-build phase started"
      - |
        # After build phase, we're in logic-legends-app, so go up to source root
        # First, check where we are
        CURRENT_DIR=$(pwd)
        echo "Current directory: $CURRENT_DIR"
        
        # Check if appspec.yml is in current directory (we're at source root)
        if [ -f "appspec.yml" ]; then
          SOURCE_ROOT=$(pwd)
        elif [ -f "../appspec.yml" ]; then
          # We're in logic-legends-app, go up one level
          SOURCE_ROOT=$(cd .. && pwd)
          cd "$SOURCE_ROOT"
        else
          # Try going up one more level
          SOURCE_ROOT=$(cd ../.. && pwd)
          cd "$SOURCE_ROOT"
        fi
        
        echo "Source root: $SOURCE_ROOT"
        echo "Current directory after navigation: $(pwd)"
        echo "Files in source root:"
        ls -la | head -15
        
        # Verify appspec.yml exists in source root
        if [ ! -f "appspec.yml" ]; then
          echo "ERROR: appspec.yml not found in source root: $SOURCE_ROOT"
          echo "Looking for appspec.yml..."
          find . -name "appspec.yml" -type f 2>/dev/null || echo "Not found anywhere"
          ls -la "$SOURCE_ROOT" | head -20
          exit 1
        fi
        echo "✅ appspec.yml found at: $SOURCE_ROOT/appspec.yml"
        
        # Prepare deployment package in a temp directory
        DEPLOY_DIR="/tmp/deploy-package"
        rm -rf "$DEPLOY_DIR"
        mkdir -p "$DEPLOY_DIR"
        
        echo "Copying application files..."
        # Copy built application from logic-legends-app
        if [ -d "$SOURCE_ROOT/logic-legends-app" ]; then
          cp -r "$SOURCE_ROOT/logic-legends-app"/* "$DEPLOY_DIR/" || { echo "ERROR: Failed to copy app files"; exit 1; }
        else
          echo "ERROR: logic-legends-app directory not found in $SOURCE_ROOT"
          exit 1
        fi
        
        echo "Installing production dependencies..."
        cd "$DEPLOY_DIR"
        npm install --production || { echo "ERROR: Failed to install production deps"; exit 1; }
        
        echo "Copying CodeDeploy files..."
        # Copy appspec.yml and scripts from source root to deployment directory
        cp "$SOURCE_ROOT/appspec.yml" . || { echo "ERROR: Failed to copy appspec.yml from $SOURCE_ROOT"; exit 1; }
        cp -R "$SOURCE_ROOT/scripts" . || { echo "ERROR: Failed to copy scripts from $SOURCE_ROOT"; exit 1; }
        chmod +x scripts/*.sh || true
        
        # Verify appspec.yml is at root of deployment directory
        echo "Verifying appspec.yml at deployment root..."
        ls -la appspec.yml || { echo "ERROR: appspec.yml not found at deployment root!"; exit 1; }
        echo "✅ appspec.yml found at: $(pwd)/appspec.yml"
        
        echo "Creating deployment zip package..."
        echo "Files to be zipped:"
        ls -la | head -20
        
        # Create zip from deployment directory - appspec.yml MUST be at root
        echo "Creating zip from deployment directory..."
        cd "$DEPLOY_DIR"
        zip -r "$SOURCE_ROOT/app.zip" . \
          -x "*.git*" \
          -x "*.md" \
          -x "*.log" \
          -x "buildspec.yml" \
          -x ".github/*" \
          -x "DEPLOYMENT_NOTES.md" \
          -x "README.md" || { echo "ERROR: Failed to create zip"; exit 1; }
        
        cd "$SOURCE_ROOT"
        
        echo "=== VERIFYING ZIP STRUCTURE ==="
        echo "Zip file location: $(pwd)/app.zip"
        echo "Zip file size: $(du -h app.zip)"
        echo ""
        echo "Full zip contents (showing all entries):"
        unzip -l app.zip
        echo ""
        echo "=== CHECKING FOR appspec.yml ==="
        
        # Check if appspec.yml exists at root (exact match, no leading path)
        if unzip -l app.zip 2>/dev/null | awk 'NR>3 && NF>=4 {print $4}' | grep -xE "appspec\.yml$" > /dev/null; then
          echo "✅ appspec.yml found at ROOT level of zip"
        else
          echo "❌ ERROR: appspec.yml NOT found at root level!"
          echo "All files in zip:"
          unzip -l app.zip | awk 'NR>3 && NF>=4 {print $4}'
          echo "Looking for appspec.yml anywhere..."
          unzip -l app.zip | grep -i appspec || echo "❌ No appspec.yml found anywhere!"
          exit 1
        fi
        
        # Test extraction to verify
        echo "Testing extraction of appspec.yml..."
        mkdir -p /tmp/zip-test
        cd /tmp/zip-test
        unzip -j "$SOURCE_ROOT/app.zip" appspec.yml 2>&1 || {
          echo "❌ ERROR: Could not extract appspec.yml from zip!"
          exit 1
        }
        if [ -f appspec.yml ]; then
          echo "✅ Successfully extracted appspec.yml"
          echo "First 10 lines of appspec.yml:"
          head -10 appspec.yml
          rm -rf /tmp/zip-test
        else
          echo "❌ ERROR: appspec.yml file not found after extraction!"
          rm -rf /tmp/zip-test
          exit 1
        fi
      - 'echo "Package created: app.zip"'
      - echo "Skipping manual CodeDeploy trigger; CodePipeline Deploy stage will handle deployment."

artifacts:
  files:
    - app.zip
  name: app.zip

cache:
  paths:
    - logic-legends-app/node_modules/**/*