version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Changing to logic-legends-app directory..."
      - |
        cd logic-legends-app || { echo "Error: logic-legends-app directory not found!"; exit 1; }
        echo "Installing dependencies..."
        if [ -f package-lock.json ]; then 
          echo "Using npm ci"
          npm ci
        else 
          echo "Lockfile not found, using npm install"
          npm install
        fi
        echo "Dependencies installed successfully"
      
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building TypeScript application..."
      - |
        cd logic-legends-app
        npm run build
        echo "Build completed on `date`"
      
  post_build:
    commands:
      - echo "Post-build phase started"
      - |
        cd logic-legends-app
        echo "Installing production dependencies..."
        npm install --production
        echo "Including CodeDeploy manifest and hooks..."
        cp ../appspec.yml . || { echo "ERROR: Failed to copy appspec.yml"; exit 1; }
        cp -R ../scripts . || { echo "ERROR: Failed to copy scripts"; exit 1; }
        chmod +x scripts/*.sh || true
        
        # Verify appspec.yml exists before zipping
        echo "Verifying appspec.yml exists..."
        ls -la appspec.yml || { echo "ERROR: appspec.yml not found in logic-legends-app/"; exit 1; }
        echo "✅ appspec.yml found at: $(pwd)/appspec.yml"
        
        echo "Creating deployment package..."
        # Create zip file - appspec.yml MUST be at root level
        zip -r ../app.zip . -x "*.git*" -x "*.md" -x "*.log" -x "buildspec.yml" -x ".github/*" || { echo "ERROR: Failed to create zip"; exit 1; }
        
        cd ..
        
        # Verify appspec.yml is in the zip at ROOT level
        echo "Verifying appspec.yml is in zip at root level..."
        unzip -l app.zip | grep -E "^.*appspec\.yml$" || { 
          echo "ERROR: appspec.yml not found in zip at root level!"
          echo "Zip contents:"
          unzip -l app.zip | head -20
          exit 1
        }
        echo "✅ appspec.yml verified in zip file at root level"
      - 'echo "Package created: app.zip"'
      - echo "Skipping manual CodeDeploy trigger; CodePipeline Deploy stage will handle deployment."

artifacts:
  files:
    - app.zip
  name: app.zip

cache:
  paths:
    - logic-legends-app/node_modules/**/*